### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 3.94 GiB already allocated; 11.12 MiB free; 4.05 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by Bonbonwjj** [psh01087/Vid-ODE#2]
i have changed batch_size to 4 but it can also not work. Who can help me, thanks a lot

**Comment by psh01087** [comment]
Your GPUs should have enough VRAM. If you get CUDA out of memory error after some epochs, it's due to ODE. Neural-ODE requires a more sufficient GPU memory size because a dynamic number of layers is forwarded in neural-ODE.
